pkg/beacon/expire.go, pkg/beacon/expire_test.go, pkg/beacon/majority.go, pkg/beacon/store/block.go, pkg/beacon/store/state.go, pkg/cache/ttl.go, pkg/cache/ttl_test.go
This change swaps the `ttl` cache (used to store `state` and `block` items) to expire individual items at a point in time rather than when they were last accessed. If the cache is full, the item closest to expiry will be evicted to make room.
This will let us keep a sliding window of `n days` of blocks for state root/block root lookups, and provides nicer garauntees for data availability for the rest of the app.
=> refactor(cache): Expire individual items based on point-in-time

pkg/beacon/majority.go, pkg/beacon/metrics.go
This fixes a bug that would stop checkpointz from serving the latest finalized checkpoint if the single attempt to download the block/state for the checkpoint failed.
We now check every 1 second if the `head` is different to the epoch we're serving. If they're different, we download the bundle. If the download fails we sleep for 30s and try again next loop.
=> feat: Download serving bundle in a queue

pkg/beacon/default.go, pkg/checkpointz/checkpointz.go
The concept of "majority" has been moved to the `beacon/checkpoints` package, so this struct is really our default implementation of the `checkpointz/beacon/FinalityProvider`.
=> refactor: Rename majority provider to default provider

example_config.yaml, pkg/beacon/default.go, pkg/beacon/download.go
Since we constantly try to backfill our store with historical blocks, the service will constantly try to download the last `n` slots on the epoch boundary, even if they don't have a block.
This change sets a limit on the amount of failures we can have per slot. Unfortunately we can't tell definitively tell if a failure was the result of a network issue, db issue, or if the block doesn't exist in the canonical finalized chain.
=> feat: Ban historical slots without a block

pkg/api/handler.go
This endpoint can be used by k8s readiness checks to safely rollout a checkpointz deployment without downtime
=> feat(api): Add checkpointz/ready endpoint

go.mod, go.sum
Sets the `beacon.Api` http client timeout to 90s (was 10s).
=> feat(beacon): Bump to version 0.3.0

pkg/beacon/config.go
Error if the historical_epoch_count is greater than the amount of blocks we can store
=> feat: Check for valid historical_epoch_count value

pkg/beacon/default.go, pkg/beacon/download.go, pkg/eth/networks.go
Adds a fallback method of deriving the network name if `spec.CONFIG_NAME` is empty
=> feat: Add deposit network id -> network name map

pkg/beacon/download.go
This fixes a bug where checkpointz would constantly try to download the genesis block over and over again. This is usually fine, but in the case of Goerli (where the first slot had an empty block) using Lodestar, this call fails. Other clients seem to handle this case ok. 
This means that end-clients that depend on the genesis state/block being available, like Prysm, will not be able to use checkpointz if its running against Goerli with a Lodestar upstream.
=> feat: Add genesis block to historical boundary checking

pkg/beacon/download.go
_just in case_ someone sets their historical limit to something crazy
=> feat: Add sleep when downloading historical blocks

go.mod, go.sum
This bumps the dep for `samcm/beacon` to `v0.4.0`, which contained a change to fetch finality after the wall clock tells us that an epoch has finished. This should result in checkpointz picking up the new finalized checkpoint quicker.
=> feat: Bump beacon to 0.4.0

.gitignore, go.mod, go.sum, pkg/api/handler.go, pkg/api/http.go, pkg/api/response.go, pkg/beacon/default.go, pkg/beacon/finality_provider.go, pkg/beacon/nodes.go, pkg/eth/string.go, pkg/service/checkpointz/checkpointz.go, pkg/service/eth/eth.go, pkg/service/eth/types.go
This change adds additional APIs that allows Checkpointz to be used as a beacon node upstream from another Checkpointz instance.
This faciliates building a chain of trust that could look something like this in the real world:
```mermaid
graph TD
A{Sam's Checkpointz} --> B{Local Beacon Node 1}
A --> D{Community Checkpointz A} --> E{Infura}
D --> F{Local Beacon Node}
G{Community Checkpointz A} --> E{Infura}
A --> G{Community Checkpointz B} --> H
H{Community Checkpointz C} --> I{Local Beacon Node}
```
=> feat: Add additional routes for checkpointz upstream

.github/actions/checkpoint-sync/action.yaml, pkg/beacon/default.go, pkg/beacon/download.go, pkg/beacon/store/block.go, pkg/beacon/store/deposit_snapshot.go, pkg/beacon/store/state.go, pkg/cache/ttl.go, pkg/cache/ttl_test.go
This change simplifies the way we store beacon blocks/states (aka "bundles".) This lets us serve the latest finalized epoch for longer (2 weeks), leaning on the cache to clear out old bundles for us. 
This allows us to continue serving bundles in the case where finality is halted for much longer:
Previously: 3 hours of serving the latest finality bundle
With this change: 2 weeks of serving the latest finaly bundle
In the case of a non-finality event greater than 2 weeks, Checkpointz can be restarted to start the 2 week clock again.
While it's tempting to store these bundles forever, doing so would potentially serve a state to a client that falls outside of the weak subjectivity period. While we can calculate that on the fly, that's a larger piece of work that needs to be done. 2 weeks …
=> feat: Refactor beacon blocks/state storage

.golangci.yml, example_config.yaml, go.mod, go.sum, pkg/beacon/node/config.go, pkg/beacon/nodes.go
This change allows users to provide headers when connecting to upstream beacon nodes
=> feat: Update beacon to v0.25.0 and add headers to config

go.mod, go.sum
This includes https://github.com/ethpandaops/beacon/pull/20 which improves beacon node compatibility with the Deposit Snapshot endpoint
=> feat: Bump ethpandaops/beacon to v0.28.0

goreleaser-debian.Dockerfile
allows us to: 
- use a Let's Encrypt certificate on the BN
- manage the system's CA trust to add self-signed CA's
=> add `ca-certificates` package to `debian` image

pkg/cache/ttl.go
Solves https://github.com/ethpandaops/checkpointz/issues/117
=> cache: refactor, and fix of race condition between expiration goroutine and external calls.

pkg/beacon/default.go
This was removed at the start of the year from the `ethpandaops/beacon` package, so we're re-adding it here in checkpointz to hopefully fix the case where an epoch transition takes a little longer
=> feat: Check for finality every 3m

web/src/parts/get-started/GetStarted.tsx, web/src/parts/get-started/GetStartedSelection.tsx
Teku now takes in a new flag: https://docs.teku.consensys.io/get-started/checkpoint-start
=> fix: teku checkpoint sync url

pkg/api/handler.go, pkg/beacon/default.go, pkg/beacon/download.go, pkg/beacon/finality_provider.go, pkg/service/eth/eth.go
- Refreshes the spec every epoch to handle a case where `X_FORK_EPOCH` is changed in upstream beacon nodes
- Fixed a panic that could occur if someone requested the `deposit_snapshot` before the finalized checkpoint was determined
- Added support for the `indices` parameter on the blob_sidecar route
- Improved bootup speed by fetching spec/genesis data immediately after establishing that we have at least 1 healthy upstream node.
=> fix: Refresh spec on epoch change

.github/actions/checkpoint-sync/action.yaml, .github/workflows/goreleaser.yaml, .github/workflows/integration.yaml, .github/workflows/manual-integration.yaml, pkg/api/handler.go, pkg/beacon/default.go, pkg/beacon/download.go, pkg/beacon/finality_provider.go, pkg/beacon/store/state.go, pkg/service/eth/eth.go
This PR changes how Checkpointz parses `beacon state` objects. Previously we just stored the raw bytes that were received from the upstream beacon node. This was becoming more and more painful as we try to comply with the Beacon API Spec as much as possible. We now fetch the state, parse it in to a struct, and marshal it to SSZ when someone requests it, allowing us to be more compliant with the Beacon API Spec.
=> feat: Parse Beacon State

goreleaser-debian.Dockerfile
This PR adds the `curl` package to the debian docker images.
Having a base utility for http requests within the container is very helpful for customized liveness probes, which require fetching some APIs and check the results to see if checkpointz is still fine.
=> add `curl` to debian docker images

.github/actions/checkpoint-sync/action.yaml, .github/workflows/alpha-releases.yaml, .github/workflows/golangci-lint.yaml, .github/workflows/goreleaser.yaml, .github/workflows/integration.yaml, .github/workflows/manual-integration.yaml, .github/workflows/test.yaml
This PR updates GitHub Actions to use pinned commit hashes for better security.
=> Update GitHub Actions to use pinned hashes

.github/dependabot.yml, .golangci.yml, pkg/beacon/download.go, pkg/service/eth/eth.go, renovate.json
This commit replaces Renovate with Dependabot for managing dependency updates. Dependabot is configured to update GitHub Actions and Go module dependencies weekly.
Renovate configuration file is removed.
=> chore: replace renovate with dependabot for dependency updates
